In [89]:
import apimoex
import requests

import string

import pandas as pd
import numpy as np

import time
from tqdm import tqdm

import matplotlib.pyplot as plt
import seaborn as sns

from scipy.stats import norm
from scipy.optimize import minimize

from datetime import datetime

%load_ext autoreload
%autoreload 2
import parsing


import sys
import warnings
warnings.filterwarnings("ignore")

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

# Парсер опциона

### Парсер №1. Первая версия. Более медленный

Данный парсер предоставляет самую свободную настройку по парсингу данных опциона (базовый актив, страйки, тип, историю торгов и т.д.)

In [81]:
base_active = 'SR'
strikes_str = [f'{int(x)}' if x == int(x) else f'{x:.1f}' for x in np.arange(240, 370, 10)]
opt_type = 'C' # европейский
months = string.ascii_uppercase # call: A-L, put: M-X
years = ['5']
weeks_flg = ['', 'A', 'B', 'C', 'D', 'E']

In [16]:
ticket_info, end_day_info = parsing.option_data_parser(base_active, strikes_str, opt_type, months, years)

2025 year is being parsed
- month: A

Week: -:   8%|█████▋                                                                    | 1/13 [00:00<00:09,  1.31it/s]

SR240CA5
Saved.

Week: -:  15%|███████████▍                                                              | 2/13 [00:01<00:06,  1.72it/s]

SR250CA5
Saved.

Week: -:  23%|█████████████████                                                         | 3/13 [00:03<00:13,  1.32s/it]

SR260CA5
Saved.

Week: -:  31%|██████████████████████▊                                                   | 4/13 [00:04<00:10,  1.19s/it]

SR270CA5
Saved.

Week: -:  38%|████████████████████████████▍                                             | 5/13 [00:05<00:09,  1.18s/it]

SR280CA5
Saved.

Week: -:  46%|██████████████████████████████████▏                                       | 6/13 [00:06<00:06,  1.03it/s]

SR290CA5
Saved.

Week: -:  54%|███████████████████████████████████████▊                                  | 7/13 [00:06<00:05,  1.19it/s]

SR300CA5
Saved.

Week: -:  62%|█████████████████████████████████████████████▌                            | 8/13 [00:07<00:03,  1.39it/s]

SR310CA5
Saved.

Week: -:  69%|███████████████████████████████████████████████████▏                      | 9/13 [00:07<00:02,  1.61it/s]

SR320CA5
Saved.

Week: -:  77%|████████████████████████████████████████████████████████▏                | 10/13 [00:08<00:01,  1.76it/s]

SR330CA5
Saved.

Week: -: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:09<00:00,  1.44it/s]
Week: A: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:05<00:00,  2.20it/s]
Week: B:   8%|█████▋                                                                    | 1/13 [00:00<00:04,  2.68it/s]

SR240CA5B
Saved.

Week: B:  15%|███████████▍                                                              | 2/13 [00:00<00:04,  2.45it/s]

SR250CA5B
Saved.

Week: B:  23%|█████████████████                                                         | 3/13 [00:01<00:05,  1.91it/s]

SR260CA5B
Saved.

Week: B:  31%|██████████████████████▊                                                   | 4/13 [00:02<00:04,  1.80it/s]

SR270CA5B
Saved.

Week: B:  38%|████████████████████████████▍                                             | 5/13 [00:02<00:05,  1.60it/s]

SR280CA5B
Saved.

Week: B:  46%|██████████████████████████████████▏                                       | 6/13 [00:03<00:04,  1.68it/s]

SR290CA5B
Saved.

Week: B:  54%|███████████████████████████████████████▊                                  | 7/13 [00:04<00:03,  1.52it/s]

SR300CA5B
Saved.

Week: B:  62%|█████████████████████████████████████████████▌                            | 8/13 [00:04<00:02,  1.73it/s]

SR310CA5B
Saved.

Week: B:  77%|████████████████████████████████████████████████████████▏                | 10/13 [00:05<00:01,  2.12it/s]

SR330CA5B
Saved.

Week: B: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:06<00:00,  1.90it/s]
Week: C: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:05<00:00,  2.56it/s]
Week: D:   8%|█████▋                                                                    | 1/13 [00:00<00:04,  2.74it/s]

SR240CA5D
Saved.

Week: D:  15%|███████████▍                                                              | 2/13 [00:00<00:04,  2.28it/s]

SR250CA5D
Saved.

Week: D:  23%|█████████████████                                                         | 3/13 [00:01<00:04,  2.41it/s]

SR260CA5D
Saved.

Week: D:  31%|██████████████████████▊                                                   | 4/13 [00:02<00:05,  1.60it/s]

SR270CA5D
Saved.

Week: D:  38%|████████████████████████████▍                                             | 5/13 [00:02<00:04,  1.69it/s]

SR280CA5D
Saved.

Week: D:  46%|██████████████████████████████████▏                                       | 6/13 [00:03<00:04,  1.74it/s]

SR290CA5D
Saved.

Week: D:  54%|███████████████████████████████████████▊                                  | 7/13 [00:03<00:03,  1.95it/s]

SR300CA5D
Saved.

Week: D:  62%|█████████████████████████████████████████████▌                            | 8/13 [00:04<00:02,  2.00it/s]

SR310CA5D
Saved.

Week: D:  69%|███████████████████████████████████████████████████▏                      | 9/13 [00:04<00:01,  2.16it/s]

SR320CA5D
Saved.

Week: D: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:06<00:00,  2.11it/s]
Week: E:   8%|█████▋                                                                    | 1/13 [00:00<00:09,  1.26it/s]

SR240CA5E
Saved.

Week: E:  15%|███████████▍                                                              | 2/13 [00:01<00:09,  1.16it/s]

SR250CA5E
Saved.

Week: E:  23%|█████████████████                                                         | 3/13 [00:02<00:06,  1.57it/s]

SR260CA5E
Saved.

Week: E:  31%|██████████████████████▊                                                   | 4/13 [00:02<00:05,  1.66it/s]

SR270CA5E
Saved.

Week: E:  38%|████████████████████████████▍                                             | 5/13 [00:03<00:04,  1.77it/s]

SR280CA5E
Saved.

Week: E:  46%|██████████████████████████████████▏                                       | 6/13 [00:03<00:04,  1.62it/s]

SR290CA5E
Saved.

Week: E:  54%|███████████████████████████████████████▊                                  | 7/13 [00:04<00:03,  1.83it/s]

SR300CA5E
Saved.

Week: E:  62%|█████████████████████████████████████████████▌                            | 8/13 [00:04<00:03,  1.64it/s]

SR310CA5E
Saved.

Week: E:  69%|███████████████████████████████████████████████████▏                      | 9/13 [00:05<00:02,  1.66it/s]

SR320CA5E
Saved.

Week: E: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:07<00:00,  1.83it/s]

- month: B

Week: -:   8%|█████▋                                                                    | 1/13 [00:00<00:07,  1.56it/s]

SR240CB5
Saved.

Week: -:  15%|███████████▍                                                              | 2/13 [00:01<00:05,  1.93it/s]

SR250CB5
Saved.

Week: -:  23%|█████████████████                                                         | 3/13 [00:01<00:05,  1.83it/s]

SR260CB5
Saved.

Week: -:  31%|██████████████████████▊                                                   | 4/13 [00:02<00:05,  1.50it/s]

SR270CB5
Saved.

Week: -:  38%|████████████████████████████▍                                             | 5/13 [00:03<00:05,  1.45it/s]

SR280CB5
Saved.

Week: -:  46%|██████████████████████████████████▏                                       | 6/13 [00:05<00:08,  1.17s/it]

SR290CB5
Saved.

Week: -:  54%|███████████████████████████████████████▊                                  | 7/13 [00:05<00:06,  1.00s/it]

SR300CB5
Saved.

Week: -:  62%|█████████████████████████████████████████████▌                            | 8/13 [00:06<00:04,  1.11it/s]

SR310CB5
Saved.

Week: -:  69%|███████████████████████████████████████████████████▏                      | 9/13 [00:07<00:03,  1.32it/s]

SR320CB5
Saved.

Week: -:  77%|████████████████████████████████████████████████████████▏                | 10/13 [00:07<00:01,  1.50it/s]

SR330CB5
Saved.

Week: -:  85%|█████████████████████████████████████████████████████████████▊           | 11/13 [00:08<00:01,  1.68it/s]

SR340CB5
Saved.

Week: -:  92%|███████████████████████████████████████████████████████████████████▍     | 12/13 [00:08<00:00,  1.82it/s]

SR350CB5
Saved.

Week: -: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:09<00:00,  1.38it/s]

SR360CB5
Saved.

Week: A:  15%|███████████▍                                                              | 2/13 [00:01<00:07,  1.47it/s]

SR250CB5A
Saved.

Week: A:  23%|█████████████████                                                         | 3/13 [00:03<00:11,  1.15s/it]

SR260CB5A
Saved.

Week: A:  31%|██████████████████████▊                                                   | 4/13 [00:06<00:18,  2.02s/it]

SR270CB5A
Saved.

Week: A:  38%|████████████████████████████▍                                             | 5/13 [00:06<00:11,  1.46s/it]

SR280CB5A
Saved.

Week: A:  46%|██████████████████████████████████▏                                       | 6/13 [00:07<00:08,  1.28s/it]

SR290CB5A
Saved.

Week: A:  54%|███████████████████████████████████████▊                                  | 7/13 [00:09<00:08,  1.43s/it]

SR300CB5A
Saved.

Week: A:  62%|█████████████████████████████████████████████▌                            | 8/13 [00:09<00:05,  1.10s/it]

SR310CB5A
Saved.

Week: A: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:11<00:00,  1.10it/s]
Week: B:  15%|███████████▍                                                              | 2/13 [00:00<00:04,  2.27it/s]

SR250CB5B
Saved.

Week: B:  23%|█████████████████                                                         | 3/13 [00:01<00:04,  2.32it/s]

SR260CB5B
Saved.

Week: B:  31%|██████████████████████▊                                                   | 4/13 [00:01<00:03,  2.42it/s]

SR270CB5B
Saved.

Week: B:  38%|████████████████████████████▍                                             | 5/13 [00:02<00:03,  2.13it/s]

SR280CB5B
Saved.

Week: B:  46%|██████████████████████████████████▏                                       | 6/13 [00:03<00:04,  1.52it/s]

SR290CB5B
Saved.

Week: B:  54%|███████████████████████████████████████▊                                  | 7/13 [00:03<00:04,  1.50it/s]

SR300CB5B
Saved.

Week: B:  62%|█████████████████████████████████████████████▌                            | 8/13 [00:04<00:02,  1.71it/s]

SR310CB5B
Saved.

Week: B: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:06<00:00,  2.11it/s]
Week: C: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:04<00:00,  2.69it/s]
Week: D:  15%|███████████▍                                                              | 2/13 [00:00<00:04,  2.71it/s]

SR250CB5D
Saved.

Week: D:  23%|█████████████████                                                         | 3/13 [00:01<00:04,  2.30it/s]

SR260CB5D
Saved.

Week: D:  31%|██████████████████████▊                                                   | 4/13 [00:01<00:03,  2.28it/s]

SR270CB5D
Saved.

Week: D:  38%|████████████████████████████▍                                             | 5/13 [00:02<00:03,  2.42it/s]

SR280CB5D
Saved.

Week: D:  46%|██████████████████████████████████▏                                       | 6/13 [00:02<00:02,  2.48it/s]

SR290CB5D
Saved.

Week: D:  54%|███████████████████████████████████████▊                                  | 7/13 [00:02<00:02,  2.31it/s]

SR300CB5D
Saved.

Week: D:  62%|█████████████████████████████████████████████▌                            | 8/13 [00:03<00:02,  2.27it/s]

SR310CB5D
Saved.

Week: D:  69%|███████████████████████████████████████████████████▏                      | 9/13 [00:08<00:07,  1.80s/it]

SR320CB5D
Saved.

Week: D:  77%|████████████████████████████████████████████████████████▏                | 10/13 [00:08<00:04,  1.45s/it]

SR330CB5D
Saved.

Week: D:  85%|█████████████████████████████████████████████████████████████▊           | 11/13 [00:10<00:02,  1.38s/it]

SR340CB5D
Saved.

Week: D:  92%|███████████████████████████████████████████████████████████████████▍     | 12/13 [00:10<00:01,  1.21s/it]

SR350CB5D
Saved.

Week: D: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:11<00:00,  1.12it/s]

SR360CB5D
Saved.

Week: E: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:05<00:00,  2.17it/s]

- month: C

Week: -:   8%|█████▋                                                                    | 1/13 [00:01<00:20,  1.74s/it]

SR240CC5
Saved.

Week: -:  15%|███████████▍                                                              | 2/13 [00:02<00:13,  1.26s/it]

SR250CC5
Saved.

Week: -:  23%|█████████████████                                                         | 3/13 [00:04<00:13,  1.39s/it]

SR260CC5
Saved.

Week: -:  31%|██████████████████████▊                                                   | 4/13 [00:05<00:12,  1.35s/it]

SR270CC5
Saved.

Week: -:  38%|████████████████████████████▍                                             | 5/13 [00:06<00:08,  1.12s/it]

SR280CC5
Saved.

Week: -:  46%|██████████████████████████████████▏                                       | 6/13 [00:06<00:06,  1.05it/s]

SR290CC5
Saved.

Week: -:  54%|███████████████████████████████████████▊                                  | 7/13 [00:08<00:07,  1.18s/it]

SR300CC5
Saved.

Week: -:  62%|█████████████████████████████████████████████▌                            | 8/13 [00:09<00:06,  1.27s/it]

SR310CC5
Saved.

Week: -:  69%|███████████████████████████████████████████████████▏                      | 9/13 [00:11<00:05,  1.34s/it]

SR320CC5
Saved.

Week: -:  77%|████████████████████████████████████████████████████████▏                | 10/13 [00:12<00:03,  1.32s/it]

SR330CC5
Saved.

Week: -:  85%|█████████████████████████████████████████████████████████████▊           | 11/13 [00:13<00:02,  1.28s/it]

SR340CC5
Saved.

Week: -:  92%|███████████████████████████████████████████████████████████████████▍     | 12/13 [00:17<00:01,  1.95s/it]

SR350CC5
Saved.

Week: -: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:22<00:00,  1.72s/it]

SR360CC5
Saved.

Week: A:  31%|██████████████████████▊                                                   | 4/13 [00:07<00:17,  1.94s/it]

SR270CC5A
Saved.

Week: A:  38%|████████████████████████████▍                                             | 5/13 [00:07<00:11,  1.45s/it]

SR280CC5A
Saved.

Week: A:  46%|██████████████████████████████████▏                                       | 6/13 [00:10<00:14,  2.08s/it]

SR290CC5A
Saved.

Week: A:  54%|███████████████████████████████████████▊                                  | 7/13 [00:11<00:09,  1.60s/it]

SR300CC5A
Saved.

Week: A:  62%|█████████████████████████████████████████████▌                            | 8/13 [00:12<00:06,  1.25s/it]

SR310CC5A
Saved.

Week: A:  69%|███████████████████████████████████████████████████▏                      | 9/13 [00:12<00:03,  1.01it/s]

SR320CC5A
Saved.

Week: A:  77%|████████████████████████████████████████████████████████▏                | 10/13 [00:12<00:02,  1.26it/s]

SR330CC5A
Saved.

Week: A:  85%|█████████████████████████████████████████████████████████████▊           | 11/13 [00:13<00:01,  1.43it/s]

SR340CC5A
Saved.

Week: A:  92%|███████████████████████████████████████████████████████████████████▍     | 12/13 [00:13<00:00,  1.61it/s]

SR350CC5A
Saved.

Week: A: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:14<00:00,  1.13s/it]
Week: B:  38%|████████████████████████████▍                                             | 5/13 [00:04<00:07,  1.13it/s]

SR280CC5B
Saved.

Week: B:  46%|██████████████████████████████████▏                                       | 6/13 [00:04<00:05,  1.34it/s]

SR290CC5B
Saved.

Week: B:  54%|███████████████████████████████████████▊                                  | 7/13 [00:05<00:04,  1.47it/s]

SR300CC5B
Saved.

Week: B:  62%|█████████████████████████████████████████████▌                            | 8/13 [00:05<00:03,  1.58it/s]

SR310CC5B
Saved.

Week: B:  69%|███████████████████████████████████████████████████▏                      | 9/13 [00:06<00:02,  1.61it/s]

SR320CC5B
Saved.

Week: B:  77%|████████████████████████████████████████████████████████▏                | 10/13 [00:06<00:01,  1.81it/s]

SR330CC5B
Saved.

Week: B:  85%|█████████████████████████████████████████████████████████████▊           | 11/13 [00:07<00:00,  2.03it/s]

SR340CC5B
Saved.

Week: B:  92%|███████████████████████████████████████████████████████████████████▍     | 12/13 [00:07<00:00,  2.16it/s]

SR350CC5B
Saved.

Week: B: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:07<00:00,  1.63it/s]
Week: C: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:05<00:00,  2.45it/s]
Week: D: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:05<00:00,  2.35it/s]
Week: E: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:04<00:00,  2.66it/s]

- month: D

Week: -:  46%|██████████████████████████████████▏                                       | 6/13 [00:02<00:02,  2.87it/s]

SR290CD5
Saved.

Week: -:  54%|███████████████████████████████████████▊                                  | 7/13 [00:02<00:02,  2.70it/s]

SR300CD5
Saved.

Week: -:  62%|█████████████████████████████████████████████▌                            | 8/13 [00:03<00:01,  2.71it/s]

SR310CD5
Saved.

Week: -:  69%|███████████████████████████████████████████████████▏                      | 9/13 [00:03<00:01,  2.77it/s]

SR320CD5
Saved.

Week: -:  92%|███████████████████████████████████████████████████████████████████▍     | 12/13 [00:04<00:00,  2.38it/s]

SR350CD5
Saved.

Week: -: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:05<00:00,  2.50it/s]

SR360CD5
Saved.

Week: A: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:05<00:00,  2.32it/s]
Week: B: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:04<00:00,  2.69it/s]
Week: C: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:06<00:00,  2.05it/s]
Week: D: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:04<00:00,  2.66it/s]
Week: E: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:05<00:00,  2.50it/s]

- month: E

Week: -: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:04<00:00,  2.87it/s]
Week: A: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:06<00:00,  1.87it/s]
Week: B: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:06<00:00,  1.93it/s]
Week: C: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:06<00:00,  1.89it/s]
Week: D: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:05<00:00,  2.53it/s]
Week: E: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:06<00:00,  2.14it/s]

- month: F

Week: -:   8%|█████▋                                                                    | 1/13 [00:01<00:18,  1.56s/it]

SR240CF5
Saved.

Week: -:  15%|███████████▍                                                              | 2/13 [00:02<00:14,  1.32s/it]

SR250CF5
Saved.

Week: -:  23%|█████████████████                                                         | 3/13 [00:03<00:10,  1.04s/it]

SR260CF5
Saved.

Week: -:  31%|██████████████████████▊                                                   | 4/13 [00:03<00:07,  1.19it/s]

SR270CF5
Saved.

Week: -:  38%|████████████████████████████▍                                             | 5/13 [00:04<00:06,  1.29it/s]

SR280CF5
Saved.

Week: -:  46%|██████████████████████████████████▏                                       | 6/13 [00:05<00:04,  1.48it/s]

SR290CF5
Saved.

Week: -:  54%|███████████████████████████████████████▊                                  | 7/13 [00:05<00:03,  1.57it/s]

SR300CF5
Saved.

Week: -:  62%|█████████████████████████████████████████████▌                            | 8/13 [00:06<00:03,  1.45it/s]

SR310CF5
Saved.

Week: -:  69%|███████████████████████████████████████████████████▏                      | 9/13 [00:06<00:02,  1.60it/s]

SR320CF5
Saved.

Week: -:  77%|████████████████████████████████████████████████████████▏                | 10/13 [00:07<00:01,  1.70it/s]

SR330CF5
Saved.

Week: -:  85%|█████████████████████████████████████████████████████████████▊           | 11/13 [00:08<00:01,  1.65it/s]

SR340CF5
Saved.

Week: -:  92%|███████████████████████████████████████████████████████████████████▍     | 12/13 [00:08<00:00,  1.57it/s]

SR350CF5
Saved.

Week: -: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:09<00:00,  1.41it/s]

SR360CF5
Saved.

Week: A: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:07<00:00,  1.84it/s]
Week: B: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:05<00:00,  2.38it/s]
Week: C: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:04<00:00,  2.63it/s]
Week: D: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:05<00:00,  2.58it/s]
Week: E: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:05<00:00,  2.41it/s]

- month: G

Week: -: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:07<00:00,  1.81it/s]
Week: A: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:04<00:00,  2.67it/s]
Week: B: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:05<00:00,  2.50it/s]
Week: C: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:04<00:00,  2.62it/s]
Week: D: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:07<00:00,  1.75it/s]
Week: E: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:05<00:00,  2.36it/s]

- month: H

Week: -: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:05<00:00,  2.45it/s]
Week: A: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:06<00:00,  1.87it/s]
Week: B: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:05<00:00,  2.51it/s]
Week: C: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:04<00:00,  2.63it/s]
Week: D: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:04<00:00,  2.67it/s]
Week: E: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:06<00:00,  2.15it/s]

- month: I

Week: -:   8%|█████▋                                                                    | 1/13 [00:01<00:12,  1.08s/it]

SR240CI5
Saved.

Week: -:  15%|███████████▍                                                              | 2/13 [00:01<00:07,  1.45it/s]

SR250CI5
Saved.

Week: -:  23%|█████████████████                                                         | 3/13 [00:02<00:09,  1.10it/s]

SR260CI5
Saved.

Week: -:  31%|██████████████████████▊                                                   | 4/13 [00:03<00:06,  1.42it/s]

SR270CI5
Saved.

Week: -:  38%|████████████████████████████▍                                             | 5/13 [00:03<00:04,  1.67it/s]

SR280CI5
Saved.

Week: -:  46%|██████████████████████████████████▏                                       | 6/13 [00:04<00:04,  1.57it/s]

SR290CI5
Saved.

Week: -:  54%|███████████████████████████████████████▊                                  | 7/13 [00:06<00:07,  1.17s/it]

SR300CI5
Saved.

Week: -:  62%|█████████████████████████████████████████████▌                            | 8/13 [00:07<00:04,  1.03it/s]

SR310CI5
Saved.

Week: -:  69%|███████████████████████████████████████████████████▏                      | 9/13 [00:07<00:03,  1.21it/s]

SR320CI5
Saved.

Week: -:  77%|████████████████████████████████████████████████████████▏                | 10/13 [00:07<00:02,  1.44it/s]

SR330CI5
Saved.

Week: -:  85%|█████████████████████████████████████████████████████████████▊           | 11/13 [00:08<00:01,  1.63it/s]

SR340CI5
Saved.

Week: -:  92%|███████████████████████████████████████████████████████████████████▍     | 12/13 [00:08<00:00,  1.82it/s]

SR350CI5
Saved.

Week: -: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:09<00:00,  1.41it/s]

SR360CI5
Saved.

Week: A: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:04<00:00,  2.89it/s]
Week: B: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:08<00:00,  1.62it/s]
Week: C: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:05<00:00,  2.55it/s]
Week: D: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:04<00:00,  3.02it/s]
Week: E: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:04<00:00,  2.94it/s]

- month: J

Week: -: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:05<00:00,  2.58it/s]
Week: A: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:04<00:00,  3.16it/s]
Week: B: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:05<00:00,  2.18it/s]
Week: C: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:03<00:00,  3.25it/s]
Week: D: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:04<00:00,  2.77it/s]
Week: E: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:04<00:00,  2.61it/s]

- month: K

Week: -: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:05<00:00,  2.53it/s]
Week: A: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:04<00:00,  2.97it/s]
Week: B: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:04<00:00,  2.84it/s]
Week: C: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:04<00:00,  2.91it/s]
Week: D: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:04<00:00,  2.91it/s]
Week: E: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:04<00:00,  3.23it/s]

- month: L

Week: -: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:04<00:00,  2.88it/s]
Week: A: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:05<00:00,  2.42it/s]
Week: B: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:04<00:00,  3.00it/s]
Week: C: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:04<00:00,  2.72it/s]
Week: D: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:04<00:00,  3.08it/s]
Week: E: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:04<00:00,  2.63it/s]

- month: M

Week: -:   8%|█████▋                                                                    | 1/13 [00:00<00:11,  1.08it/s]

SR240CM5
Saved.

Week: -:  15%|███████████▍                                                              | 2/13 [00:01<00:09,  1.22it/s]

SR250CM5
Saved.

Week: -:  23%|█████████████████                                                         | 3/13 [00:02<00:07,  1.42it/s]

SR260CM5
Saved.

Week: -:  31%|██████████████████████▊                                                   | 4/13 [00:02<00:05,  1.68it/s]

SR270CM5
Saved.

Week: -:  38%|████████████████████████████▍                                             | 5/13 [00:03<00:04,  1.72it/s]

SR280CM5
Saved.

Week: -:  46%|██████████████████████████████████▏                                       | 6/13 [00:03<00:03,  1.97it/s]

SR290CM5
Saved.

Week: -:  54%|███████████████████████████████████████▊                                  | 7/13 [00:03<00:02,  2.21it/s]

SR300CM5
Saved.

Week: -:  62%|█████████████████████████████████████████████▌                            | 8/13 [00:04<00:02,  2.24it/s]

SR310CM5
Saved.

Week: -:  69%|███████████████████████████████████████████████████▏                      | 9/13 [00:04<00:01,  2.45it/s]

SR320CM5
Saved.

Week: -:  77%|████████████████████████████████████████████████████████▏                | 10/13 [00:05<00:01,  2.53it/s]

SR330CM5
Saved.

Week: -: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:06<00:00,  2.15it/s]
Week: A: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:05<00:00,  2.56it/s]
Week: B:   8%|█████▋                                                                    | 1/13 [00:00<00:04,  2.68it/s]

SR240CM5B
Saved.

Week: B:  15%|███████████▍                                                              | 2/13 [00:00<00:04,  2.55it/s]

SR250CM5B
Saved.

Week: B:  23%|█████████████████                                                         | 3/13 [00:01<00:03,  2.69it/s]

SR260CM5B
Saved.

Week: B:  31%|██████████████████████▊                                                   | 4/13 [00:01<00:03,  2.45it/s]

SR270CM5B
Saved.

Week: B:  38%|████████████████████████████▍                                             | 5/13 [00:02<00:03,  2.21it/s]

SR280CM5B
Saved.

Week: B:  46%|██████████████████████████████████▏                                       | 6/13 [00:02<00:02,  2.41it/s]

SR290CM5B
Saved.

Week: B:  54%|███████████████████████████████████████▊                                  | 7/13 [00:02<00:02,  2.42it/s]

SR300CM5B
Saved.

Week: B:  62%|█████████████████████████████████████████████▌                            | 8/13 [00:03<00:02,  2.43it/s]

SR310CM5B
Saved.

Week: B: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:05<00:00,  2.51it/s]
Week: C: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:05<00:00,  2.29it/s]
Week: D:   8%|█████▋                                                                    | 1/13 [00:00<00:06,  1.89it/s]

SR240CM5D
Saved.

Week: D:  15%|███████████▍                                                              | 2/13 [00:00<00:04,  2.26it/s]

SR250CM5D
Saved.

Week: D:  23%|█████████████████                                                         | 3/13 [00:01<00:03,  2.54it/s]

SR260CM5D
Saved.

Week: D:  31%|██████████████████████▊                                                   | 4/13 [00:01<00:03,  2.25it/s]

SR270CM5D
Saved.

Week: D:  38%|████████████████████████████▍                                             | 5/13 [00:02<00:03,  2.04it/s]

SR280CM5D
Saved.

Week: D:  46%|██████████████████████████████████▏                                       | 6/13 [00:02<00:03,  2.19it/s]

SR290CM5D
Saved.

Week: D:  54%|███████████████████████████████████████▊                                  | 7/13 [00:03<00:02,  2.16it/s]

SR300CM5D
Saved.

Week: D:  62%|█████████████████████████████████████████████▌                            | 8/13 [00:03<00:02,  2.07it/s]

SR310CM5D
Saved.

Week: D:  69%|███████████████████████████████████████████████████▏                      | 9/13 [00:04<00:01,  2.25it/s]

SR320CM5D
Saved.

Week: D: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:05<00:00,  2.37it/s]
Week: E:   8%|█████▋                                                                    | 1/13 [00:01<00:13,  1.12s/it]

SR240CM5E
Saved.

Week: E:  15%|███████████▍                                                              | 2/13 [00:01<00:09,  1.19it/s]

SR250CM5E
Saved.

Week: E:  23%|█████████████████                                                         | 3/13 [00:02<00:08,  1.19it/s]

SR260CM5E
Saved.

Week: E:  31%|██████████████████████▊                                                   | 4/13 [00:03<00:06,  1.38it/s]

SR270CM5E
Saved.

Week: E:  38%|████████████████████████████▍                                             | 5/13 [00:03<00:05,  1.37it/s]

SR280CM5E
Saved.

Week: E:  46%|██████████████████████████████████▏                                       | 6/13 [00:04<00:05,  1.40it/s]

SR290CM5E
Saved.

Week: E:  54%|███████████████████████████████████████▊                                  | 7/13 [00:04<00:03,  1.64it/s]

SR300CM5E
Saved.

Week: E:  62%|█████████████████████████████████████████████▌                            | 8/13 [00:05<00:03,  1.66it/s]

SR310CM5E
Saved.

Week: E: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:07<00:00,  1.80it/s]

- month: N

Week: -:   8%|█████▋                                                                    | 1/13 [00:00<00:05,  2.31it/s]

SR240CN5
Saved.

Week: -:  15%|███████████▍                                                              | 2/13 [00:00<00:04,  2.60it/s]

SR250CN5
Saved.

Week: -:  23%|█████████████████                                                         | 3/13 [00:01<00:05,  1.72it/s]

SR260CN5
Saved.

Week: -:  31%|██████████████████████▊                                                   | 4/13 [00:02<00:05,  1.64it/s]

SR270CN5
Saved.

Week: -:  38%|████████████████████████████▍                                             | 5/13 [00:03<00:05,  1.45it/s]

SR280CN5
Saved.

Week: -:  46%|██████████████████████████████████▏                                       | 6/13 [00:03<00:04,  1.52it/s]

SR290CN5
Saved.

Week: -:  54%|███████████████████████████████████████▊                                  | 7/13 [00:04<00:03,  1.64it/s]

SR300CN5
Saved.

Week: -:  62%|█████████████████████████████████████████████▌                            | 8/13 [00:04<00:02,  1.69it/s]

SR310CN5
Saved.

Week: -:  69%|███████████████████████████████████████████████████▏                      | 9/13 [00:05<00:02,  1.91it/s]

SR320CN5
Saved.

Week: -:  77%|████████████████████████████████████████████████████████▏                | 10/13 [00:05<00:01,  2.11it/s]

SR330CN5
Saved.

Week: -:  85%|█████████████████████████████████████████████████████████████▊           | 11/13 [00:05<00:00,  2.26it/s]

SR340CN5
Saved.

Week: -:  92%|███████████████████████████████████████████████████████████████████▍     | 12/13 [00:06<00:00,  2.27it/s]

SR350CN5
Saved.

Week: -: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:06<00:00,  1.95it/s]

SR360CN5
Saved.

Week: A:  15%|███████████▍                                                              | 2/13 [00:00<00:04,  2.69it/s]

SR250CN5A
Saved.

Week: A:  23%|█████████████████                                                         | 3/13 [00:01<00:03,  2.64it/s]

SR260CN5A
Saved.

Week: A:  31%|██████████████████████▊                                                   | 4/13 [00:01<00:03,  2.44it/s]

SR270CN5A
Saved.

Week: A:  38%|████████████████████████████▍                                             | 5/13 [00:01<00:03,  2.65it/s]

SR280CN5A
Saved.

Week: A:  46%|██████████████████████████████████▏                                       | 6/13 [00:02<00:02,  2.34it/s]

SR290CN5A
Saved.

Week: A:  54%|███████████████████████████████████████▊                                  | 7/13 [00:02<00:02,  2.31it/s]

SR300CN5A
Saved.

Week: A:  62%|█████████████████████████████████████████████▌                            | 8/13 [00:03<00:02,  2.48it/s]

SR310CN5A
Saved.

Week: A:  69%|███████████████████████████████████████████████████▏                      | 9/13 [00:03<00:01,  2.49it/s]

SR320CN5A
Saved.

Week: A: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:04<00:00,  2.72it/s]
Week: B:  15%|███████████▍                                                              | 2/13 [00:00<00:04,  2.61it/s]

SR250CN5B
Saved.

Week: B:  23%|█████████████████                                                         | 3/13 [00:01<00:03,  2.64it/s]

SR260CN5B
Saved.

Week: B:  31%|██████████████████████▊                                                   | 4/13 [00:01<00:03,  2.45it/s]

SR270CN5B
Saved.

Week: B:  38%|████████████████████████████▍                                             | 5/13 [00:01<00:03,  2.49it/s]

SR280CN5B
Saved.

Week: B:  46%|██████████████████████████████████▏                                       | 6/13 [00:02<00:03,  2.02it/s]

SR290CN5B
Saved.

Week: B:  54%|███████████████████████████████████████▊                                  | 7/13 [00:03<00:02,  2.05it/s]

SR300CN5B
Saved.

Week: B:  62%|█████████████████████████████████████████████▌                            | 8/13 [00:03<00:02,  2.22it/s]

SR310CN5B
Saved.

Week: B:  69%|███████████████████████████████████████████████████▏                      | 9/13 [00:03<00:01,  2.35it/s]

SR320CN5B
Saved.

Week: B: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:05<00:00,  2.54it/s]
Week: C: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:04<00:00,  2.90it/s]
Week: D:  15%|███████████▍                                                              | 2/13 [00:00<00:04,  2.75it/s]

SR250CN5D
Saved.

Week: D:  23%|█████████████████                                                         | 3/13 [00:01<00:04,  2.49it/s]

SR260CN5D
Saved.

Week: D:  31%|██████████████████████▊                                                   | 4/13 [00:01<00:03,  2.36it/s]

SR270CN5D
Saved.

Week: D:  38%|████████████████████████████▍                                             | 5/13 [00:02<00:04,  1.83it/s]

SR280CN5D
Saved.

Week: D:  46%|██████████████████████████████████▏                                       | 6/13 [00:02<00:03,  2.07it/s]

SR290CN5D
Saved.

Week: D:  54%|███████████████████████████████████████▊                                  | 7/13 [00:03<00:02,  2.05it/s]

SR300CN5D
Saved.

Week: D:  62%|█████████████████████████████████████████████▌                            | 8/13 [00:03<00:02,  2.07it/s]

SR310CN5D
Saved.

Week: D:  69%|███████████████████████████████████████████████████▏                      | 9/13 [00:04<00:01,  2.16it/s]

SR320CN5D
Saved.

Week: D:  77%|████████████████████████████████████████████████████████▏                | 10/13 [00:04<00:01,  2.31it/s]

SR330CN5D
Saved.

Week: D:  85%|█████████████████████████████████████████████████████████████▊           | 11/13 [00:04<00:00,  2.47it/s]

SR340CN5D
Saved.

Week: D:  92%|███████████████████████████████████████████████████████████████████▍     | 12/13 [00:05<00:00,  2.58it/s]

SR350CN5D
Saved.

Week: D: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:05<00:00,  2.31it/s]
Week: E: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:05<00:00,  2.59it/s]

- month: O

Week: -:   8%|█████▋                                                                    | 1/13 [00:00<00:06,  1.96it/s]

SR240CO5
Saved.

Week: -:  15%|███████████▍                                                              | 2/13 [00:01<00:07,  1.39it/s]

SR250CO5
Saved.

Week: -:  23%|█████████████████                                                         | 3/13 [00:05<00:23,  2.30s/it]

SR260CO5
Saved.

Week: -:  31%|██████████████████████▊                                                   | 4/13 [00:06<00:15,  1.71s/it]

SR270CO5
Saved.

Week: -:  38%|████████████████████████████▍                                             | 5/13 [00:09<00:17,  2.19s/it]

SR280CO5
Saved.

Week: -:  46%|██████████████████████████████████▏                                       | 6/13 [00:10<00:11,  1.66s/it]

SR290CO5
Saved.

Week: -:  54%|███████████████████████████████████████▊                                  | 7/13 [00:11<00:09,  1.51s/it]

SR300CO5
Saved.

Week: -:  62%|█████████████████████████████████████████████▌                            | 8/13 [00:11<00:06,  1.24s/it]

SR310CO5
Saved.

Week: -:  69%|███████████████████████████████████████████████████▏                      | 9/13 [00:12<00:04,  1.03s/it]

SR320CO5
Saved.

Week: -:  77%|████████████████████████████████████████████████████████▏                | 10/13 [00:13<00:02,  1.11it/s]

SR330CO5
Saved.

Week: -:  85%|█████████████████████████████████████████████████████████████▊           | 11/13 [00:14<00:01,  1.03it/s]

SR340CO5
Saved.

Week: -:  92%|███████████████████████████████████████████████████████████████████▍     | 12/13 [00:15<00:01,  1.17s/it]

SR350CO5
Saved.

Week: -: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:16<00:00,  1.25s/it]

SR360CO5
Saved.

Week: A:  31%|██████████████████████▊                                                   | 4/13 [00:01<00:03,  2.71it/s]

SR270CO5A
Saved.

Week: A:  38%|████████████████████████████▍                                             | 5/13 [00:01<00:03,  2.59it/s]

SR280CO5A
Saved.

Week: A:  46%|██████████████████████████████████▏                                       | 6/13 [00:02<00:02,  2.59it/s]

SR290CO5A
Saved.

Week: A:  54%|███████████████████████████████████████▊                                  | 7/13 [00:02<00:02,  2.56it/s]

SR300CO5A
Saved.

Week: A:  62%|█████████████████████████████████████████████▌                            | 8/13 [00:03<00:02,  2.20it/s]

SR310CO5A
Saved.

Week: A:  69%|███████████████████████████████████████████████████▏                      | 9/13 [00:05<00:04,  1.04s/it]

SR320CO5A
Saved.

Week: A:  77%|████████████████████████████████████████████████████████▏                | 10/13 [00:07<00:03,  1.20s/it]

SR330CO5A
Saved.

Week: A:  85%|█████████████████████████████████████████████████████████████▊           | 11/13 [00:08<00:02,  1.33s/it]

SR340CO5A
Saved.

Week: A:  92%|███████████████████████████████████████████████████████████████████▍     | 12/13 [00:09<00:01,  1.03s/it]

SR350CO5A
Saved.

Week: A: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:09<00:00,  1.37it/s]
Week: B:  38%|████████████████████████████▍                                             | 5/13 [00:02<00:03,  2.55it/s]

SR280CO5B
Saved.

Week: B:  46%|██████████████████████████████████▏                                       | 6/13 [00:02<00:02,  2.65it/s]

SR290CO5B
Saved.

Week: B:  54%|███████████████████████████████████████▊                                  | 7/13 [00:02<00:02,  2.71it/s]

SR300CO5B
Saved.

Week: B:  62%|█████████████████████████████████████████████▌                            | 8/13 [00:03<00:01,  2.50it/s]

SR310CO5B
Saved.

Week: B:  69%|███████████████████████████████████████████████████▏                      | 9/13 [00:04<00:02,  1.75it/s]

SR320CO5B
Saved.

Week: B:  77%|████████████████████████████████████████████████████████▏                | 10/13 [00:04<00:01,  1.92it/s]

SR330CO5B
Saved.

Week: B: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:05<00:00,  2.22it/s]
Week: C: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:04<00:00,  2.78it/s]
Week: D: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:17<00:00,  1.31s/it]
Week: E: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:05<00:00,  2.43it/s]

- month: P

Week: -:  31%|██████████████████████▊                                                   | 4/13 [00:01<00:02,  3.07it/s]

SR270CP5
Saved.

Week: -: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:04<00:00,  2.96it/s]
Week: A: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:04<00:00,  2.99it/s]
Week: B: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:05<00:00,  2.59it/s]
Week: C: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:04<00:00,  2.72it/s]
Week: D: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:04<00:00,  2.89it/s]
Week: E: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:04<00:00,  3.11it/s]

- month: Q

Week: -: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:04<00:00,  2.83it/s]
Week: A: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:04<00:00,  3.01it/s]
Week: B: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:05<00:00,  2.42it/s]
Week: C: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:06<00:00,  1.94it/s]
Week: D: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:04<00:00,  2.72it/s]
Week: E: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:04<00:00,  2.87it/s]

- month: R

Week: -:   8%|█████▋                                                                    | 1/13 [00:00<00:05,  2.04it/s]

SR240CR5
Saved.

Week: -:  15%|███████████▍                                                              | 2/13 [00:00<00:04,  2.36it/s]

SR250CR5
Saved.

Week: -:  23%|█████████████████                                                         | 3/13 [00:01<00:04,  2.49it/s]

SR260CR5
Saved.

Week: -:  31%|██████████████████████▊                                                   | 4/13 [00:01<00:03,  2.31it/s]

SR270CR5
Saved.

Week: -:  38%|████████████████████████████▍                                             | 5/13 [00:03<00:06,  1.24it/s]

SR280CR5
Saved.

Week: -:  46%|██████████████████████████████████▏                                       | 6/13 [00:04<00:05,  1.22it/s]

SR290CR5
Saved.

Week: -:  54%|███████████████████████████████████████▊                                  | 7/13 [00:04<00:03,  1.50it/s]

SR300CR5
Saved.

Week: -:  62%|█████████████████████████████████████████████▌                            | 8/13 [00:04<00:02,  1.79it/s]

SR310CR5
Saved.

Week: -:  69%|███████████████████████████████████████████████████▏                      | 9/13 [00:05<00:02,  1.76it/s]

SR320CR5
Saved.

Week: -:  77%|████████████████████████████████████████████████████████▏                | 10/13 [00:05<00:01,  1.82it/s]

SR330CR5
Saved.

Week: -:  85%|█████████████████████████████████████████████████████████████▊           | 11/13 [00:06<00:00,  2.03it/s]

SR340CR5
Saved.

Week: -: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:06<00:00,  1.90it/s]

SR360CR5
Saved.

Week: A: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:04<00:00,  3.07it/s]
Week: B: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:05<00:00,  2.25it/s]
Week: C: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:04<00:00,  3.04it/s]
Week: D: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:04<00:00,  2.90it/s]
Week: E: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:05<00:00,  2.20it/s]

- month: S

Week: -: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:04<00:00,  2.61it/s]
Week: A: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:05<00:00,  2.50it/s]
Week: B: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:05<00:00,  2.54it/s]
Week: C: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:06<00:00,  1.93it/s]
Week: D: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:06<00:00,  2.00it/s]
Week: E: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:06<00:00,  2.11it/s]

- month: T

Week: -: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:04<00:00,  2.68it/s]
Week: A: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:04<00:00,  2.73it/s]
Week: B: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:04<00:00,  2.84it/s]
Week: C: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:06<00:00,  2.09it/s]
Week: D: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:05<00:00,  2.26it/s]
Week: E: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:04<00:00,  2.93it/s]

- month: U

Week: -:   8%|█████▋                                                                    | 1/13 [00:00<00:06,  1.79it/s]

SR240CU5
Saved.

Week: -:  15%|███████████▍                                                              | 2/13 [00:01<00:06,  1.68it/s]

SR250CU5
Saved.

Week: -:  23%|█████████████████                                                         | 3/13 [00:02<00:11,  1.14s/it]

SR260CU5
Saved.

Week: -:  31%|██████████████████████▊                                                   | 4/13 [00:03<00:07,  1.14it/s]

SR270CU5
Saved.

Week: -:  38%|████████████████████████████▍                                             | 5/13 [00:03<00:05,  1.42it/s]

SR280CU5
Saved.

Week: -:  46%|██████████████████████████████████▏                                       | 6/13 [00:04<00:04,  1.70it/s]

SR290CU5
Saved.

Week: -:  54%|███████████████████████████████████████▊                                  | 7/13 [00:06<00:06,  1.03s/it]

SR300CU5
Saved.

Week: -:  62%|█████████████████████████████████████████████▌                            | 8/13 [00:06<00:04,  1.21it/s]

SR310CU5
Saved.

Week: -:  69%|███████████████████████████████████████████████████▏                      | 9/13 [00:06<00:02,  1.42it/s]

SR320CU5
Saved.

Week: -:  77%|████████████████████████████████████████████████████████▏                | 10/13 [00:07<00:01,  1.67it/s]

SR330CU5
Saved.

Week: -: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:08<00:00,  1.49it/s]
Week: A: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:04<00:00,  2.73it/s]
Week: B: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:04<00:00,  2.99it/s]
Week: C: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:04<00:00,  3.05it/s]
Week: D: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:04<00:00,  3.21it/s]
Week: E: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:04<00:00,  2.96it/s]

- month: V

Week: -: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:04<00:00,  2.82it/s]
Week: A: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:04<00:00,  2.81it/s]
Week: B: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:05<00:00,  2.59it/s]
Week: C: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:05<00:00,  2.42it/s]
Week: D: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:05<00:00,  2.23it/s]
Week: E: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:04<00:00,  2.70it/s]

- month: W

Week: -: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:04<00:00,  2.78it/s]
Week: A: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:05<00:00,  2.37it/s]
Week: B: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:04<00:00,  2.70it/s]
Week: C: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:04<00:00,  2.62it/s]
Week: D: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:05<00:00,  2.59it/s]
Week: E: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:09<00:00,  1.36it/s]

- month: X

Week: -: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:04<00:00,  2.83it/s]
Week: A: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:04<00:00,  2.94it/s]
Week: B: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:04<00:00,  3.17it/s]
Week: C: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:04<00:00,  3.08it/s]
Week: D: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:04<00:00,  3.12it/s]
Week: E: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:04<00:00,  2.91it/s]

- month: Y

Week: -: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:04<00:00,  3.06it/s]
Week: A: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:04<00:00,  3.08it/s]
Week: B: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:05<00:00,  2.41it/s]
Week: C: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:06<00:00,  2.02it/s]
Week: D: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:07<00:00,  1.66it/s]
Week: E: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:05<00:00,  2.50it/s]

- month: Z

Week: -: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:05<00:00,  2.22it/s]
Week: A:  92%|███████████████████████████████████████████████████████████████████▍     | 12/13 [00:26<00:06,  6.75s/it]

Произошла ошибка типа: ConnectTimeout

Week: A: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:27<00:00,  2.11s/it]
Week: B: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:05<00:00,  2.44it/s]
Week: C: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:05<00:00,  2.52it/s]
Week: D: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:05<00:00,  2.58it/s]
Week: E: 100%|█████████████████████████████████████████████████████████████████████████| 13/13 [00:05<00:00,  2.36it/s]

In [17]:
ticket_info.to_csv('ticker_info_SBER.csv', index=False) 
end_day_info.to_csv('end_day_info_SBER.csv', index=False)

In [22]:
ticket_info.head(2)

,Краткий код,Наименование серии инструмента,Краткое наименование контракта,Последний день обращения,Тип опциона,Дата исполнения,Код базового актива,Начало обращения,Вид опциона пут или колл,Цена Страйк,...,Наименование контракта,Группа контрактов,Котировка,Базовый актив,Клиринг исполнения,Опционная серия,Вид контракта,Код типа инструмента,Тип бумаги,Типа инструмента
0,SR240CA5,Прем. европ. Call 240 с исп. 15 янв. на SBER,SBERP150125CE240,2025-01-15,Расчетный,2025-01-15,SBRF,2024-11-06,C,240,...,Опцион колл на обыкновенные акции ПАО «Сбербан...,Акции,В рублях за 1 акцию,SBER,Основной,SBERP150125XE,Опцион на акции,futures_options,option_on_shares,Опционы
1,SR250CA5,Прем. европ. Call 250 с исп. 15 янв. на SBER,SBERP150125CE250,2025-01-15,Расчетный,2025-01-15,SBRF,2024-11-06,C,250,...,Опцион колл на обыкновенные акции ПАО «Сбербан...,Акции,В рублях за 1 акцию,SBER,Основной,SBERP150125XE,Опцион на акции,futures_options,option_on_shares,Опционы

In [25]:
end_day_info.head(2)

,NAME,BOARDID,TRADEDATE,SECID,OPEN,LOW,HIGH,CLOSE,OPENPOSITIONVALUE,VALUE,VOLUME,OPENPOSITION,SETTLEPRICE,WAPRICE,SETTLEPRICEDAY,CHANGE,QTY,NUMTRADES
0,SR240CA5,ROPD,2024-11-06,SR240CA5,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,19.73,NaN,NaN,NaN,NaN,0
1,SR240CA5,ROPD,2024-11-07,SR240CA5,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,22.20,NaN,NaN,NaN,NaN,0

In [29]:
len(ticket_info)

264

### Пример использования

In [77]:
# Возьмем какой-то опцион для примера
ticket_info[ticket_info['Краткий код'] == 'SR330CU5']

,Краткий код,Наименование серии инструмента,Краткое наименование контракта,Последний день обращения,Тип опциона,Дата исполнения,Код базового актива,Начало обращения,Вид опциона пут или колл,Цена Страйк,...,Наименование контракта,Группа контрактов,Котировка,Базовый актив,Клиринг исполнения,Опционная серия,Вид контракта,Код типа инструмента,Тип бумаги,Типа инструмента
263,SR330CU5,Прем. европ. Put 330 с исп. 17 сент. на SBER,SBERP170925PE330,2025-09-17,Расчетный,2025-09-17,SBRF,2024-09-23,P,330,...,Опцион пут на обыкновенные акции ПАО «Сбербанк...,Акции,В рублях за 1 акцию,SBER,Основной,SBERP170925XE,Опцион на акции,futures_options,option_on_shares,Опционы

In [78]:
# Все опционы данной серии с разными страйками на 2024-12-09
pattern = r'^SR\d+(\.\d+)?CU5$'
filtered_df = end_day_info[end_day_info['NAME'].str.contains(pattern)]
option_strikes = filtered_df.merge(ticket_info[['Краткий код', 'Цена Страйк']], how='left', left_on='NAME', right_on='Краткий код')
option_info = option_strikes[option_strikes['TRADEDATE'] == '2024-12-09'][['NAME', 'TRADEDATE', 'SETTLEPRICE', 'Цена Страйк']]
option_info

         NAME   TRADEDATE  SETTLEPRICE Цена Страйк
55   SR240CU5  2024-12-09        20.79         240
167  SR250CU5  2024-12-09        24.36         250
279  SR260CU5  2024-12-09        28.35         260
631  SR300CU5  2024-12-09        48.43         300

In [80]:
# Все опционы данной серии, за весь период обращения со страйком 240
pattern = r'^SR240CA5$'
filtered_df = end_day_info[end_day_info['NAME'].str.contains(pattern)]
option_strikes = filtered_df.merge(ticket_info[['Краткий код', 'Цена Страйк']], how='left', left_on='NAME', right_on='Краткий код')
option_info = option_strikes[['NAME', 'TRADEDATE', 'SETTLEPRICE', 'Цена Страйк']]
option_info

        NAME   TRADEDATE  SETTLEPRICE Цена Страйк
0   SR240CA5  2024-11-06        19.73         240
1   SR240CA5  2024-11-07        22.20         240
2   SR240CA5  2024-11-08        24.93         240
3   SR240CA5  2024-11-11        31.00         240
4   SR240CA5  2024-11-12        27.40         240
5   SR240CA5  2024-11-13        29.45         240
6   SR240CA5  2024-11-14        21.42         240
7   SR240CA5  2024-11-15        24.49         240
8   SR240CA5  2024-11-18        22.09         240
9   SR240CA5  2024-11-19        15.18         240
10  SR240CA5  2024-11-20        13.24         240
11  SR240CA5  2024-11-21        13.11         240
12  SR240CA5  2024-11-22        16.05         240
13  SR240CA5  2024-11-25        19.99         240
14  SR240CA5  2024-11-26        12.07         240
15  SR240CA5  2024-11-27         8.10         240
16  SR240CA5  2024-11-28        13.94         240
17  SR240CA5  2024-11-29        15.65         240
18  SR240CA5  2024-12-02        19.42         240
19  SR240CA5  2024-12-03        12.54         240
20  SR240CA5  2024-12-04        12.34         240
21  SR240CA5  2024-12-05        12.75         240
22  SR240CA5  2024-12-06        10.69         240
23  SR240CA5  2024-12-09        16.05         240
24  SR240CA5  2024-12-10        10.94         240
25  SR240CA5  2024-12-11         8.65         240
26  SR240CA5  2024-12-12         8.10         240
27  SR240CA5  2024-12-13         8.53         240
28  SR240CA5  2024-12-16         8.16         240
29  SR240CA5  2024-12-17         4.99         240
30  SR240CA5  2024-12-18         6.86         240
31  SR240CA5  2024-12-19         5.98         240
32  SR240CA5  2024-12-20        31.21         240
33  SR240CA5  2024-12-23        29.71         240
34  SR240CA5  2024-12-24        29.93         240
35  SR240CA5  2024-12-25        33.89         240
36  SR240CA5  2024-12-26        34.75         240
37  SR240CA5  2024-12-27        33.67         240
38  SR240CA5  2024-12-28        34.30         240
39  SR240CA5  2024-12-30        43.39         240
40  SR240CA5  2025-01-03        35.23         240
41  SR240CA5  2025-01-06        34.35         240
42  SR240CA5  2025-01-08        38.06         240
43  SR240CA5  2025-01-09        33.58         240
44  SR240CA5  2025-01-10        39.29         240
45  SR240CA5  2025-01-13        42.28         240
46  SR240CA5  2025-01-14        40.25         240
47  SR240CA5  2025-01-15        37.51         240

In [71]:
len(end_day_info)

11455

In [72]:
len(ticket_info)

264

## Парсер № 2. Ускоренный

In [82]:
ticket_info_2, end_day_info_2 = parsing.fast_option_data_parser(base_active, strikes_str, opt_type, months, years)

Processing options:   0%|▏                                                            | 6/2028 [00:00<03:38,  9.25it/s]

Saved SR270CA5
Saved SR320CA5
Saved SR310CA5
Saved SR260CA5
Saved SR280CA5
Saved SR240CA5
Saved SR290CA5
Saved SR330CA5
Saved SR300CA5
Saved SR250CA5

Processing options:   2%|▉                                                           | 33/2028 [00:01<00:37, 52.54it/s]

Saved SR260CA5B
Saved SR270CA5B
Saved SR250CA5B
Saved SR240CA5B
Saved SR310CA5B
Saved SR290CA5B
Saved SR330CA5B
Saved SR300CA5B
Saved SR280CA5B
Saved SR320CA5B

Processing options:   3%|█▉                                                          | 66/2028 [00:01<00:20, 94.54it/s]

Saved SR240CA5D
Saved SR270CA5D
Saved SR260CA5D
Saved SR300CA5D
Saved SR310CA5D
Saved SR250CA5D
Saved SR290CA5D
Saved SR280CA5D
Saved SR320CA5D
Saved SR330CA5D
Saved SR240CA5E
Saved SR260CA5E
Saved SR250CA5E
Saved SR270CA5E
Saved SR280CA5E
Saved SR290CA5E
Saved SR310CA5E
Saved SR330CA5E
Saved SR320CA5E
Saved SR300CA5E
Saved SR240CB5
Saved SR250CB5

Processing options:   5%|██▊                                                        | 95/2028 [00:01<00:18, 105.27it/s]

Saved SR260CB5
Saved SR270CB5
Saved SR280CB5
Saved SR290CB5
Saved SR310CB5
Saved SR300CB5
Saved SR320CB5
Saved SR340CB5
Saved SR330CB5
Saved SR350CB5
Saved SR360CB5
Saved SR240CB5A
Saved SR250CB5A
Saved SR260CB5A
Saved SR280CB5A
Saved SR270CB5A
Saved SR300CB5A
Saved SR290CB5A
Saved SR330CB5A

Processing options:   6%|███▍                                                      | 121/2028 [00:01<00:16, 112.90it/s]

Saved SR310CB5A
Saved SR320CB5A
Saved SR240CB5B
Saved SR250CB5B
Saved SR260CB5B
Saved SR280CB5B
Saved SR270CB5B
Saved SR290CB5B
Saved SR330CB5B
Saved SR310CB5B
Saved SR320CB5B
Saved SR340CB5B
Saved SR300CB5B

Processing options:   7%|████▎                                                      | 148/2028 [00:02<00:19, 96.38it/s]

Saved SR260CB5D
Saved SR280CB5D
Saved SR290CB5D
Saved SR250CB5D
Saved SR240CB5D
Saved SR270CB5D
Saved SR330CB5D
Saved SR310CB5D
Saved SR340CB5D
Saved SR350CB5D
Saved SR320CB5D
Saved SR300CB5D
Saved SR360CB5D

Processing options:   8%|████▉                                                      | 169/2028 [00:02<00:22, 83.31it/s]

Saved SR240CC5
Saved SR250CC5
Saved SR280CC5
Saved SR260CC5
Saved SR290CC5
Saved SR310CC5
Saved SR330CC5
Saved SR300CC5
Saved SR240CC5A
Saved SR250CC5A
Saved SR340CC5
Saved SR260CC5A
Saved SR280CC5A
Saved SR270CC5A
Saved SR360CC5
Saved SR350CC5
Saved SR310CC5A
Saved SR300CC5A

Processing options:   9%|█████▍                                                     | 189/2028 [00:02<00:21, 86.17it/s]

Saved SR350CC5A
Saved SR360CC5A
Saved SR320CC5A
Saved SR270CC5
Saved SR340CC5A
Saved SR320CC5
Saved SR260CC5B
Saved SR270CC5B
Saved SR290CC5B
Saved SR300CC5B
Saved SR310CC5B
Saved SR320CC5B
Saved SR290CC5A
Saved SR330CC5A
Saved SR280CC5B
Saved SR330CC5B
Saved SR340CC5B
Saved SR350CC5B
Saved SR360CC5B

Processing options:  12%|███████▏                                                  | 250/2028 [00:03<00:14, 120.68it/s]

Saved SR240CD5
Saved SR250CD5
Saved SR270CD5
Saved SR260CD5
Saved SR280CD5
Saved SR300CD5
Saved SR340CD5
Saved SR290CD5
Saved SR320CD5
Saved SR310CD5
Saved SR330CD5
Saved SR350CD5
Saved SR360CD5

Processing options:  21%|████████████                                              | 420/2028 [00:04<00:10, 154.94it/s]

Saved SR300CF5
Saved SR270CF5
Saved SR250CF5
Saved SR310CF5
Saved SR240CF5
Saved SR260CF5
Saved SR290CF5
Saved SR320CF5
Saved SR340CF5
Saved SR330CF5
Saved SR280CF5
Saved SR350CF5
Saved SR360CF5

Processing options:  31%|██████████████████▏                                       | 638/2028 [00:06<00:12, 108.84it/s]

Saved SR290CI5
Saved SR280CI5
Saved SR240CI5
Saved SR270CI5
Saved SR310CI5
Saved SR330CI5
Saved SR250CI5
Saved SR320CI5
Saved SR260CI5
Saved SR300CI5
Saved SR360CI5
Saved SR350CI5
Saved SR340CI5

Processing options:  47%|███████████████████████████                               | 947/2028 [00:08<00:08, 132.47it/s]

Saved SR240CM5
Saved SR270CM5
Saved SR260CM5
Saved SR250CM5
Saved SR320CM5
Saved SR290CM5
Saved SR330CM5
Saved SR280CM5
Saved SR310CM5
Saved SR300CM5

Processing options:  48%|███████████████████████████▉                              | 978/2028 [00:08<00:08, 130.07it/s]

Saved SR250CM5B
Saved SR240CM5B
Saved SR260CM5B
Saved SR270CM5B
Saved SR280CM5B
Saved SR290CM5B
Saved SR300CM5B
Saved SR320CM5B
Saved SR330CM5B
Saved SR310CM5B

Processing options:  49%|████████████████████████████▊                              | 992/2028 [00:08<00:11, 90.67it/s]

Saved SR250CM5D
Saved SR270CM5D
Saved SR280CM5D
Saved SR290CM5D
Saved SR310CM5D
Saved SR330CM5D
Saved SR240CM5E
Saved SR250CM5E
Saved SR260CM5E
Saved SR270CM5E
Saved SR290CM5E
Saved SR300CM5E
Saved SR310CM5E

Processing options:  50%|████████████████████████████▉                             | 1012/2028 [00:09<00:16, 62.79it/s]

Saved SR320CM5E
Saved SR330CM5E
Saved SR240CN5
Saved SR240CM5D
Saved SR260CN5
Saved SR250CN5
Saved SR290CN5
Saved SR300CM5D
Saved SR300CN5

Processing options:  51%|█████████████████████████████▍                            | 1030/2028 [00:09<00:14, 68.73it/s]

Saved SR320CM5D
Saved SR310CN5
Saved SR320CN5
Saved SR260CM5D
Saved SR340CN5
Saved SR330CN5
Saved SR280CN5
Saved SR350CN5
Saved SR360CN5
Saved SR260CN5A
Saved SR280CM5E
Saved SR280CN5A
Saved SR300CN5A
Saved SR320CN5A
Saved SR330CN5A

Processing options:  52%|██████████████████████████████▏                           | 1054/2028 [00:09<00:10, 89.68it/s]

Saved SR240CN5A
Saved SR310CN5A
Saved SR270CN5A
Saved SR240CN5B
Saved SR250CN5B
Saved SR250CN5A
Saved SR270CN5B
Saved SR270CN5
Saved SR290CN5B
Saved SR300CN5B
Saved SR330CN5B
Saved SR320CN5B
Saved SR310CN5B

Processing options:  53%|██████████████████████████████▊                           | 1076/2028 [00:09<00:10, 92.39it/s]

Saved SR240CN5D
Saved SR250CN5D
Saved SR260CN5D
Saved SR280CN5D
Saved SR270CN5D
Saved SR280CN5B
Saved SR300CN5D
Saved SR290CN5A
Saved SR260CN5B
Saved SR340CN5B
Saved SR310CN5D
Saved SR320CN5D
Saved SR290CN5D
Saved SR340CN5D
Saved SR350CN5D
Saved SR330CN5D
Saved SR360CN5D

Processing options:  54%|███████████████████████████████▌                          | 1104/2028 [00:10<00:09, 98.72it/s]

Saved SR240CO5
Saved SR250CO5
Saved SR270CO5
Saved SR300CO5
Saved SR280CO5
Saved SR290CO5
Saved SR330CO5
Saved SR260CO5
Saved SR320CO5
Saved SR310CO5
Saved SR240CO5A
Saved SR340CO5
Saved SR250CO5A
Saved SR270CO5A
Saved SR260CO5A
Saved SR350CO5

Processing options:  55%|████████████████████████████████▏                         | 1125/2028 [00:10<00:09, 92.57it/s]

Saved SR280CO5A
Saved SR290CO5A
Saved SR360CO5
Saved SR300CO5A
Saved SR320CO5A
Saved SR310CO5A
Saved SR260CO5B
Saved SR340CO5A
Saved SR270CO5B
Saved SR360CO5A
Saved SR350CO5A
Saved SR290CO5B
Saved SR330CO5A
Saved SR280CO5B
Saved SR300CO5B
Saved SR320CO5B
Saved SR310CO5B

Processing options:  57%|████████████████████████████████▋                        | 1164/2028 [00:10<00:05, 163.85it/s]

Saved SR340CO5B
Saved SR360CO5B
Saved SR350CO5B
Saved SR330CO5B
Saved SR260CP5
Saved SR250CP5
Saved SR240CP5
Saved SR290CP5
Saved SR270CP5
Saved SR310CP5

Processing options:  60%|█████████████████████████████████▉                       | 1208/2028 [00:10<00:04, 164.91it/s]

Saved SR280CP5
Saved SR300CP5
Saved SR320CP5
Saved SR340CP5
Saved SR330CP5
Saved SR350CP5
Saved SR360CP5

Processing options:  66%|█████████████████████████████████████▋                   | 1342/2028 [00:11<00:04, 139.21it/s]

Saved SR250CR5
Saved SR240CR5
Saved SR260CR5
Saved SR330CR5
Saved SR300CR5
Saved SR320CR5
Saved SR310CR5
Saved SR280CR5
Saved SR270CR5
Saved SR290CR5
Saved SR340CR5
Saved SR350CR5
Saved SR360CR5

Processing options:  78%|████████████████████████████████████████████▏            | 1574/2028 [00:13<00:03, 116.81it/s]

Saved SR270CU5
Saved SR280CU5
Saved SR250CU5
Saved SR310CU5
Saved SR290CU5
Saved SR240CU5
Saved SR320CU5
Saved SR330CU5
Saved SR260CU5
Saved SR300CU5
Saved SR360CU5
Saved SR350CU5
Saved SR340CU5

Processing options: 100%|█████████████████████████████████████████████████████████| 2028/2028 [00:16<00:00, 120.40it/s]

In [83]:
ticket_info_2.to_csv('ticker_info_SBER_2.csv', index=False) 
end_day_info_2.to_csv('end_day_info_SBER_2.csv', index=False)

In [84]:
len(ticket_info_2)

326

In [85]:
len(end_day_info_2)

12100

## Парсер № 3. Оптимизированный

In [90]:
# parallel = False
ticket_info_3, end_day_info_3 = parsing.optimizid_option_data_parser(base_active, strikes_str, opt_type, months, years, parallel=False)

Processing options:   2%|█▎                                                            | 4/184 [00:00<00:09, 18.56it/s]

Saved SR170CF5
Saved SR170CR5
Saved SR180CC5
Saved SR180CF5

Processing options:   4%|██▋                                                           | 8/184 [00:00<00:09, 18.90it/s]

Saved SR180CI5
Saved SR180CO5
Saved SR180CR5
Saved SR180CU5

Processing options:   5%|███▎                                                         | 10/184 [00:00<00:10, 16.59it/s]

Saved SR190CC5
Saved SR190CF5
Saved SR190CI5

Processing options:   8%|████▋                                                        | 14/184 [00:00<00:11, 14.52it/s]

Saved SR190CO5
Saved SR190CR5
Saved SR190CU5

Processing options:   9%|█████▎                                                       | 16/184 [00:01<00:12, 13.03it/s]

Saved SR200CC5
Saved SR200CF5
Saved SR200CI5

Processing options:  11%|██████▋                                                      | 20/184 [00:01<00:12, 13.64it/s]

Saved SR200CO5
Saved SR200CR5
Saved SR200CU5

Processing options:  12%|███████▎                                                     | 22/184 [00:01<00:12, 13.26it/s]

Saved SR210CC5
Saved SR210CF5
Saved SR210CI5

Processing options:  14%|████████▌                                                    | 26/184 [00:01<00:12, 12.66it/s]

Saved SR210CO5
Saved SR210CR5
Saved SR210CU5

Processing options:  15%|█████████▎                                                   | 28/184 [00:01<00:12, 12.64it/s]

Saved SR220CC5
Saved SR220CF5
Saved SR220CI5

Processing options:  17%|██████████▌                                                  | 32/184 [00:02<00:12, 12.32it/s]

Saved SR220CO5
Saved SR220CR5
Saved SR220CU5
Saved SR230CC5

Processing options:  20%|███████████▉                                                 | 36/184 [00:02<00:16,  8.96it/s]

Saved SR230CF5
Saved SR230CI5
Saved SR230CO5
Saved SR230CR5

Processing options:  22%|█████████████▎                                               | 40/184 [00:03<00:17,  8.26it/s]

Saved SR230CU5
Saved SR240CC5
Saved SR240CF5

Processing options:  23%|█████████████▉                                               | 42/184 [00:03<00:15,  9.31it/s]

Saved SR240CI5
Saved SR240CO5
Saved SR240CR5

Processing options:  24%|██████████████▌                                              | 44/184 [00:03<00:14,  9.85it/s]

Saved SR240CU5
Saved SR250CC5

Processing options:  26%|███████████████▉                                             | 48/184 [00:04<00:13,  9.86it/s]

Saved SR250CF5
Saved SR250CI5
Saved SR250CO5

Processing options:  27%|████████████████▌                                            | 50/184 [00:04<00:12, 10.34it/s]

Saved SR250CR5
Saved SR250CU5
Saved SR260CC5

Processing options:  29%|█████████████████▉                                           | 54/184 [00:04<00:10, 12.89it/s]

Saved SR260CC5A
Saved SR260CC5B
Saved SR260CD5
Saved SR260CF5

Processing options:  32%|███████████████████▏                                         | 58/184 [00:04<00:09, 12.95it/s]

Saved SR260CI5
Saved SR260CO5
Saved SR260CO5A
Saved SR260CO5B

Processing options:  33%|███████████████████▉                                         | 60/184 [00:05<00:08, 14.46it/s]

Saved SR260CP5
Saved SR260CR5

Processing options:  35%|█████████████████████▏                                       | 64/184 [00:05<00:09, 12.56it/s]

Saved SR260CU5
Saved SR270CC5
Saved SR270CC5A

Processing options:  36%|█████████████████████▉                                       | 66/184 [00:05<00:08, 13.80it/s]

Saved SR270CC5B
Saved SR270CD5
Saved SR270CF5

Processing options:  38%|███████████████████████▏                                     | 70/184 [00:05<00:08, 13.15it/s]

Saved SR270CI5
Saved SR270CO5
Saved SR270CO5A

Processing options:  40%|████████████████████████▌                                    | 74/184 [00:06<00:07, 13.95it/s]

Saved SR270CO5B
Saved SR270CP5
Saved SR270CR5
Saved SR270CU5
Saved SR280CC5

Processing options:  41%|█████████████████████████▏                                   | 76/184 [00:06<00:11,  9.42it/s]

Saved SR280CC5A
Saved SR280CC5B

Processing options:  43%|██████████████████████████▌                                  | 80/184 [00:06<00:10, 10.10it/s]

Saved SR280CD5
Saved SR280CF5
Saved SR280CI5

Processing options:  45%|███████████████████████████▏                                 | 82/184 [00:07<00:09, 10.29it/s]

Saved SR280CO5
Saved SR280CO5A
Saved SR280CO5B
Saved SR280CP5

Processing options:  47%|████████████████████████████▊                                | 87/184 [00:07<00:08, 11.63it/s]

Saved SR280CR5
Saved SR280CU5
Saved SR290CC5

Processing options:  49%|█████████████████████████████▊                               | 90/184 [00:07<00:06, 13.85it/s]

Saved SR290CC5A
Saved SR290CC5B
Saved SR290CD5
Saved SR290CF5

Processing options:  51%|███████████████████████████████▏                             | 94/184 [00:07<00:06, 12.92it/s]

Saved SR290CI5
Saved SR290CO5
Saved SR290CO5A

Processing options:  53%|████████████████████████████████▍                            | 98/184 [00:08<00:06, 14.08it/s]

Saved SR290CO5B
Saved SR290CP5
Saved SR290CR5
Saved SR290CU5

Processing options:  54%|████████████████████████████████▌                           | 100/184 [00:08<00:06, 12.45it/s]

Saved SR300CC5
Saved SR300CC5A
Saved SR300CC5B

Processing options:  57%|█████████████████████████████████▉                          | 104/184 [00:08<00:05, 14.39it/s]

Saved SR300CD5
Saved SR300CF5
Saved SR300CI5

Processing options:  59%|███████████████████████████████████▌                        | 109/184 [00:08<00:04, 16.15it/s]

Saved SR300CO5
Saved SR300CO5A
Saved SR300CO5B
Saved SR300CP5
Saved SR300CR5

Processing options:  60%|████████████████████████████████████▏                       | 111/184 [00:09<00:04, 14.69it/s]

Saved SR300CU5
Saved SR310CC5
Saved SR310CC5A

Processing options:  61%|████████████████████████████████████▊                       | 113/184 [00:09<00:04, 14.49it/s]

Saved SR310CC5B

Processing options:  62%|█████████████████████████████████████▌                      | 115/184 [00:09<00:06, 10.47it/s]

Saved SR310CD5
Saved SR310CF5
Saved SR310CI5

Processing options:  64%|██████████████████████████████████████▏                     | 117/184 [00:09<00:06, 10.77it/s]

Saved SR310CO5
Saved SR310CO5A

Processing options:  66%|███████████████████████████████████████▍                    | 121/184 [00:10<00:06, 10.13it/s]

Saved SR310CO5B
Saved SR310CP5
Saved SR310CR5
Saved SR310CU5

Processing options:  68%|████████████████████████████████████████▊                   | 125/184 [00:10<00:04, 12.75it/s]

Saved SR320CC5
Saved SR320CC5A
Saved SR320CC5B
Saved SR320CD5

Processing options:  71%|██████████████████████████████████████████▍                 | 130/184 [00:10<00:03, 15.39it/s]

Saved SR320CF5
Saved SR320CI5
Saved SR320CO5
Saved SR320CO5A

Processing options:  73%|███████████████████████████████████████████▋                | 134/184 [00:10<00:02, 17.04it/s]

Saved SR320CO5B
Saved SR320CP5
Saved SR320CR5
Saved SR320CU5

Processing options:  75%|█████████████████████████████████████████████               | 138/184 [00:11<00:02, 16.60it/s]

Saved SR330CC5
Saved SR330CC5A
Saved SR330CC5B
Saved SR330CD5

Processing options:  76%|█████████████████████████████████████████████▋              | 140/184 [00:11<00:02, 15.88it/s]

Saved SR330CF5
Saved SR330CI5
Saved SR330CO5

Processing options:  78%|██████████████████████████████████████████████▉             | 144/184 [00:11<00:02, 16.21it/s]

Saved SR330CO5A
Saved SR330CO5B
Saved SR330CP5
Saved SR330CR5

Processing options:  80%|████████████████████████████████████████████████▎           | 148/184 [00:11<00:02, 14.56it/s]

Saved SR330CU5
Saved SR340CC5
Saved SR340CC5A

Processing options:  82%|████████████████████████████████████████████████▉           | 150/184 [00:11<00:02, 14.29it/s]

Saved SR340CC5B
Saved SR340CD5
Saved SR340CF5

Processing options:  84%|██████████████████████████████████████████████████▏         | 154/184 [00:12<00:02, 14.78it/s]

Saved SR340CI5
Saved SR340CO5
Saved SR340CO5A
Saved SR340CO5B

Processing options:  86%|███████████████████████████████████████████████████▌        | 158/184 [00:12<00:01, 15.77it/s]

Saved SR340CP5
Saved SR340CR5
Saved SR340CU5
Saved SR350CC5

Processing options:  88%|████████████████████████████████████████████████████▊       | 162/184 [00:12<00:01, 15.77it/s]

Saved SR350CC5A
Saved SR350CC5B
Saved SR350CD5
Saved SR350CF5

Processing options:  89%|█████████████████████████████████████████████████████▍      | 164/184 [00:12<00:01, 16.44it/s]

Saved SR350CI5

Processing options:  91%|██████████████████████████████████████████████████████▊     | 168/184 [00:13<00:01, 11.57it/s]

Saved SR350CO5
Saved SR350CO5A
Saved SR350CO5B
Saved SR350CP5

Processing options:  92%|███████████████████████████████████████████████████████▍    | 170/184 [00:13<00:01, 12.68it/s]

Saved SR350CR5
Saved SR350CU5
Saved SR360CC5

Processing options:  95%|████████████████████████████████████████████████████████▋   | 174/184 [00:13<00:00, 13.09it/s]

Saved SR360CC5A
Saved SR360CC5B
Saved SR360CD5

Processing options:  97%|██████████████████████████████████████████████████████████  | 178/184 [00:14<00:00, 13.74it/s]

Saved SR360CF5
Saved SR360CI5
Saved SR360CO5
Saved SR360CO5A

Processing options:  99%|███████████████████████████████████████████████████████████▎| 182/184 [00:14<00:00, 15.78it/s]

Saved SR360CO5B
Saved SR360CP5
Saved SR360CR5
Saved SR360CU5

Processing options: 100%|████████████████████████████████████████████████████████████| 184/184 [00:14<00:00, 12.80it/s]

Saved SR370CF5
Saved SR370CR5

In [94]:
ticket_info_3.to_csv('ticker_info_SBER_3.csv', index=False) 
end_day_info_3.to_csv('end_day_info_SBER_3.csv', index=False)

In [91]:
len(ticket_info_3)

184

In [92]:
len(end_day_info_3)

13072

In [93]:
# parallel = True
ticket_info_4, end_day_info_4 = parsing.optimizid_option_data_parser(base_active, strikes_str, opt_type, months, years, parallel=True)

Processing options:   2%|█                                                             | 3/184 [00:00<00:15, 11.41it/s]

Saved SR190CF5
Saved SR190CI5
Saved SR190CO5

Processing options:   3%|█▋                                                            | 5/184 [00:00<00:15, 11.43it/s]

Saved SR190CR5
Saved SR190CU5
Saved SR200CC5

Processing options:   5%|███                                                           | 9/184 [00:00<00:14, 12.45it/s]

Saved SR200CF5
Saved SR200CI5
Saved SR170CR5

Processing options:  10%|██████▎                                                      | 19/184 [00:00<00:05, 30.55it/s]

Saved SR180CC5
Saved SR180CI5
Saved SR180CO5
Saved SR170CF5
Saved SR180CR5
Saved SR200CO5
Saved SR180CU5
Saved SR190CC5
Saved SR180CF5
Saved SR200CR5
Saved SR200CU5
Saved SR210CO5
Saved SR210CF5
Saved SR210CR5

Processing options:  17%|██████████▌                                                  | 32/184 [00:01<00:03, 40.55it/s]

Saved SR210CC5
Saved SR220CC5
Saved SR210CU5
Saved SR220CF5
Saved SR220CR5
Saved SR220CO5
Saved SR230CC5
Saved SR230CF5
Saved SR230CI5

Processing options:  22%|█████████████▎                                               | 40/184 [00:01<00:02, 49.42it/s]

Saved SR230CO5
Saved SR220CI5
Saved SR210CI5
Saved SR230CR5
Saved SR230CU5
Saved SR240CI5
Saved SR240CF5
Saved SR240CC5
Saved SR240CO5
Saved SR240CR5
Saved SR240CU5
Saved SR250CI5
Saved SR250CF5
Saved SR250CC5
Saved SR220CU5

Processing options:  32%|███████████████████▏                                         | 58/184 [00:01<00:01, 64.82it/s]

Saved SR250CO5
Saved SR260CC5A
Saved SR260CC5B
Saved SR250CR5
Saved SR250CU5
Saved SR260CC5
Saved SR260CO5A
Saved SR260CD5
Saved SR260CO5B
Saved SR260CP5
Saved SR260CF5
Saved SR260CI5
Saved SR260CO5
Saved SR270CC5A
Saved SR260CR5
Saved SR270CD5
Saved SR270CC5B
Saved SR260CU5
Saved SR270CC5
Saved SR270CO5A

Processing options:  42%|█████████████████████████▌                                   | 77/184 [00:01<00:01, 72.83it/s]

Saved SR270CI5
Saved SR270CP5
Saved SR270CU5
Saved SR270CO5B
Saved SR270CF5
Saved SR280CC5A
Saved SR280CC5B
Saved SR270CO5
Saved SR270CR5
Saved SR280CD5
Saved SR280CC5
Saved SR280CI5
Saved SR280CO5A
Saved SR280CF5
Saved SR280CP5
Saved SR280CO5B

Processing options:  52%|███████████████████████████████▍                             | 95/184 [00:01<00:01, 78.14it/s]

Saved SR280CR5
Saved SR280CU5
Saved SR290CC5A
Saved SR280CO5
Saved SR290CD5
Saved SR290CC5B
Saved SR290CI5
Saved SR290CF5
Saved SR290CC5
Saved SR290CO5B
Saved SR290CU5
Saved SR290CO5A
Saved SR290CO5
Saved SR300CC5A
Saved SR290CP5
Saved SR300CC5B
Saved SR300CD5
Saved SR300CF5
Saved SR300CO5A

Processing options:  62%|█████████████████████████████████████▏                      | 114/184 [00:02<00:00, 80.72it/s]

Saved SR290CR5
Saved SR300CC5
Saved SR300CR5
Saved SR300CO5B
Saved SR300CP5
Saved SR300CI5
Saved SR300CO5
Saved SR310CC5A
Saved SR310CC5B
Saved SR310CD5
Saved SR300CU5
Saved SR310CI5
Saved SR310CC5
Saved SR310CF5
Saved SR310CO5A
Saved SR310CP5
Saved SR310CO5B

Processing options:  72%|███████████████████████████████████████████                 | 132/184 [00:02<00:00, 83.50it/s]

Saved SR310CU5
Saved SR310CR5
Saved SR320CC5B
Saved SR320CC5A
Saved SR310CO5
Saved SR320CD5
Saved SR320CF5
Saved SR320CO5B
Saved SR320CI5
Saved SR320CO5A
Saved SR320CC5
Saved SR320CR5
Saved SR320CP5
Saved SR320CU5
Saved SR320CO5
Saved SR330CC5A
Saved SR330CD5
Saved SR330CC5B
Saved SR330CC5

Processing options:  89%|████████████████████████████████████████████████████▎      | 163/184 [00:02<00:00, 118.32it/s]

Saved SR330CF5
Saved SR330CI5
Saved SR330CO5A
Saved SR330CO5B
Saved SR330CU5
Saved SR330CR5
Saved SR330CP5
Saved SR330CO5
Saved SR340CC5A
Saved SR340CC5B
Saved SR340CF5
Saved SR340CD5
Saved SR340CI5
Saved SR340CO5A
Saved SR340CO5B
Saved SR340CP5
Saved SR340CR5
Saved SR340CU5
Saved SR340CC5
Saved SR350CC5A
Saved SR340CO5
Saved SR350CC5B
Saved SR350CF5
Saved SR350CI5
Saved SR350CD5
Saved SR350CC5
Saved SR350CO5B
Saved SR350CO5A
Saved SR350CP5
Saved SR350CR5
Saved SR350CU5
Saved SR360CC5A
Saved SR360CC5B
Saved SR360CD5
Saved SR360CI5
Saved SR350CO5
Saved SR360CF5
Saved SR360CO5B
Saved SR360CP5

Processing options: 100%|████████████████████████████████████████████████████████████| 184/184 [00:02<00:00, 68.65it/s]

Saved SR360CU5
Saved SR360CO5A
Saved SR360CR5
Saved SR360CO5
Saved SR360CC5
Saved SR370CF5
Saved SR370CR5

In [95]:
ticket_info_4.to_csv('ticker_info_SBER_4.csv', index=False) 
end_day_info_4.to_csv('end_day_info_SBER_4.csv', index=False)

In [96]:
len(ticket_info_4)

184

In [97]:
len(end_day_info_4)

13072

In [106]:
len(set(ticket_info_2['Краткий код']) - set(ticket_info_4['Краткий код']))

182

In [107]:
len(set(ticket_info_4['Краткий код']) - set(ticket_info_2['Краткий код']))

40

# Парсер базового актива

In [68]:
# на опредленную дату
asset_code = 'SBER'
start_date = '2025-02-18' 

data = parsing.get_asset_price(asset_code, start_date)
data

   TRADEDATE    OPEN   CLOSE    HIGH     LOW    VOLUME
0 2025-02-18  319.99  312.95  320.92  310.21  85001770

In [69]:
# за период

asset_code = 'SBER'
start_date = '2025-01-01' 
end_date = '2025-02-28'

data = parsing.get_asset_price(asset_code, start_date, end_date)
data

    TRADEDATE    OPEN   CLOSE    HIGH     LOW     VOLUME
0  2025-01-03  280.00  272.25  280.41  271.80   43086870
1  2025-01-06  270.88  274.37  274.41  270.07   28454750
2  2025-01-08  273.07  277.00  277.87  273.07   26634660
3  2025-01-09  276.71  271.80  278.77  270.73   52952880
4  2025-01-10  272.31  278.77  279.53  270.27   71154220
5  2025-01-13  280.62  279.80  284.75  278.60   66601710
6  2025-01-14  279.84  279.85  282.36  277.41   46037150
7  2025-01-15  280.00  282.77  282.82  276.06   52864450
8  2025-01-16  283.70  281.80  284.00  281.18   49453530
9  2025-01-17  282.20  283.53  284.64  280.19   51876150
10 2025-01-20  285.10  278.19  286.23  277.61   67946640
11 2025-01-21  279.39  281.85  281.85  276.32   40478260
12 2025-01-22  282.00  280.36  284.00  280.20   47106880
13 2025-01-23  280.79  280.49  280.79  277.35   38573410
14 2025-01-24  281.00  280.74  282.75  279.25   32155210
15 2025-01-27  280.72  275.23  280.97  275.01   39035610
16 2025-01-28  275.25  278.35  279.26  274.01   39030820
17 2025-01-29  278.00  280.36  282.18  277.12   39161630
18 2025-01-30  280.44  281.97  282.50  280.36   28020880
19 2025-01-31  281.97  280.73  284.11  280.27   40333120
20 2025-02-03  280.21  279.55  280.35  278.00   30373760
21 2025-02-04  279.55  277.40  281.41  275.70   23986670
22 2025-02-05  277.30  282.88  283.89  275.34   43070410
23 2025-02-06  283.89  287.15  288.92  282.09   69363150
24 2025-02-07  287.66  285.81  288.90  285.08   27626070
25 2025-02-10  287.61  289.94  294.55  287.61   73052590
26 2025-02-11  290.35  294.06  294.10  289.30   56009830
27 2025-02-12  294.30  314.00  314.40  291.30  185816680
28 2025-02-13  315.61  310.10  318.72  307.20  116925810
29 2025-02-14  315.59  309.87  317.84  303.06  126690930
30 2025-02-17  314.00  319.50  319.55  312.31   84827010
31 2025-02-18  319.99  312.95  320.92  310.21   85001770
32 2025-02-19  313.53  315.91  317.25  311.01   50484340
33 2025-02-20  315.91  315.05  317.96  314.02   33164900
34 2025-02-21  315.48  314.74  316.69  312.00   32725520
35 2025-02-24  314.92  316.03  316.40  313.00   35730390
36 2025-02-25  316.03  316.97  318.59  315.62   38826960
37 2025-02-26  316.97  310.22  317.45  308.31   73827020
38 2025-02-27  310.22  307.10  312.45  305.43   60936490
39 2025-02-28  306.01  309.63  310.40  304.05   65681370

In [70]:
data.to_csv('SBER_shares.csv', index=False)